### ISSUE TITLE
Can't find puppet file

### ISSUE THREAD

**Issue by c4b4d4** [simonbs/SBSCustomAnimoji#2]
No matter what I try, I always keep getting that the Apple AvatarKit cannot find the mrsquare file. Does anyone know how to fix it?

`SBSCustomAnimoji[1348:674660] [AvatarKit] can't find puppet named mrsquare`

**Comment by aloveric** [comment]
Same issue +1

**Comment by aaronn** [comment]
Same here.

**Comment by aaronn** [comment]
After some digging, I think this is because the `pathForPuppetNamed` method being swizzled has been moved from the `AVTPuppet` class to the `AVTAnimoji` class in iOS 12's AvatarKit. I think we need to generate a new `.tbd` file and update the method being swizzled.
